### ISSUE TITLE
[8.1.1] Highcharts error #32

### ISSUE THREAD

**Issue by mateuszkornecki** [blacklabel/custom_events#143] opened 2020-06-15 06:55 UTC
While working with the current Highcharts version (8.1.1) the HC error # 32 occurs.
```javascript
Highcharts error #32: www.highcharts.com/errors/32/?Highcharts.each=Array.forEach
Highcharts.each: Array.forEach
```

**Live demo:**
Steps: open console in the dev tools
https://jsfiddle.net/BlackLabel/szo9w432/

**Comment by sebastianbochan** [comment] 2020-06-15 11:28
It looks like a general issue in Highcharts. 

Related issues:
- https://github.com/highcharts/highcharts/issues/13708
- https://github.com/highcharts/highcharts/issues/9225

Close this ticket as not a bug in the plugin.

**Comment by sebastianbochan** [comment] 2020-06-16 08:02
After discussion, we agreed that its a bug.

Reopen the issue.

**Comment by mfilipiec** [comment] 2023-08-01 10:22
It doesn't seem to still be a problem, I've also tested on a few other versions and everything worked fine, the issue is to be closed.

**Closed by mfilipiec** 2023-08-01 10:22 UTC
