### ISSUE TITLE
Wrong point reference in event object.

### ISSUE THREAD

**Issue by Denyllon** [blacklabel/custom_events#127] opened 2018-09-24 11:29 UTC
### Actual Behaviour ###

When right clicking on the first point in series (close to the bottom right corner), event passed to the function has wrong point reference (next point from the series is assigned).

### Demo & steps to reproduce ###

**Live example:** https://jsfiddle.net/rafum7ye/2/

Click on the first point (close to the bottom right corner), and see the attached context menu. Also you can look at the console for logged event object.

That's most probably regression after https://github.com/blacklabel/custom_events/commit/ac8b1641b7fec8de7a006b687c9a5e6be752bc45

**[EDIT]**
Referenced to: https://github.com/blacklabel/custom_events/issues/119

**Comment by sebastianbochan** [comment] 2018-09-25 08:38
Duplicate of #119

**Comment by sebastianbochan** [comment] 2018-09-25 09:38
Issue fixed, in case when you use `plotOptions.series.events.click` the reference is to series. If you need to the point, use `plotOptions.series.point.events.click`.

**Comment by KacperMadej** [comment] 2018-09-28 13:13
There still seems to be an issue. If you click on point you get series reference in e.point - https://jsfiddle.net/BlackLabel/rafum7ye/20/ but if you click dataLabel then it works fine. It's also works correctly when custom-events is not loaded or line series is used.

@sebastianbochan

**Comment by sebastianbochan** [comment] 2018-09-28 13:19
@KacperMadej you should use `plotOptions.series.point.events`

Demo:
- https://jsfiddle.net/BlackLabel/o4x97zhc/

**Closed** 2019-03-07 13:48 UTC
