### ISSUE TITLE
This disables clicks elsewhere on the page

### ISSUE THREAD

**Issue by miguel-ribeiro** [blacklabel/custom_events#80] opened 2017-01-05 10:16 UTC
Is there a way to enable the normal contextmenu elsewhere in the page?
For me it works as expected on the chart with the callback function, but I expected the normal context menu when I click outside the chart.

**Comment by aaronhuisinga** [comment] 2017-01-12 03:39
See #74 as this is the same issue

**Comment by sebastianbochan** [comment] 2017-01-12 08:42
Duplicate of #74

**Closed by sebastianbochan** 2017-01-12 08:42 UTC
